title = "The Goood Cookie"
baseURL = "localhost:1313"
[params]
  email = "thegooodcookie@gmail.com"
  address = "6244 Dalmarnock Cresent NW"
  phone = "587 892 9353"
  facebookUrl = "https://www.facebook.com/thegooodcookie"
  instagramUrl = "https://www.instagram.com/thegooodcookie"
  clientId = "Abpj0N9cWAk4XqmQGQUzEpWmqtWukWw09XKVIC_Aim0kAvbB9eAs4sgUoMQR3HXU7vc_sUDfBdsTIdva"
  cliendIdSandbox = "AfaOSE_XfUDGQYuNRS6h5n926rmSDAzKblAhP0dVcRmELrfSYHkABK3YSAiadvXFNJ7Q7XgLOMUA2iiV"
  
languageCode = "en-ca"
disableKinds = ["section", "RSS", "taxonomy", "taxonomyTerm"]